### ISSUE TITLE
Link do artykułu

### ISSUE THREAD

**Issue by piecioshka** [rendfall/chrome-pap24#1]
Wszystko fajnie, ale przydałby się link do artykułu.
Chciałbym aby po kliknięciu w tekst otwierała mi się nowa karta z artykułem.

**Comment by piecioshka** [comment]
Ping @rendfall 😸

**Comment by rendfall** [comment]
W sekcji `Kanał RSS` linki w nagłówkach działają.
W sekcji `Serwis 24` niestety agencja nie dostarcza linków, gdyż to są najświeższe informacje i nie zawsze artykuły jeszcze powstały.
