### ISSUE TITLE
Kodowanie znaków w HTML

### ISSUE THREAD

**Issue by piecioshka** [rendfall/chrome-pap24#6]
Brakuje polskich znaków: 
https://www.dropbox.com/s/ve7vsjunga94oud/Zrzut%20ekranu%202016-05-16%2015.57.53.png?dl=0

**Comment by piecioshka** [comment]
Ping @rendfall 😄

**Comment by rendfall** [comment]
Problem rozwiązany w e7d9e6c1666e0d55aaa53a2516ccd170f941422c 
@piecioshka Dzięki za głoszenie!
